name: GolangCI Lint

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.go'

env:
    GO_VERSION: '1.24'

jobs:
    golangci-lint:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-go@v5
            with:
              go-version: ${{ env.GO_VERSION }}
          - name: lint
            uses: golangci/golangci-lint-action@v6.5.0
            with:
              version: latest
